# Vectors, matrices, and arrays in Julia

A few key ideas:
  * Julia vectors and matrices are instances of a more general multidimensional `Array` type.
  * A Julia vector is a 1-d `Array`, and a Julia matrix is a 2-d `Array`.
  * Vectors and matrices are distinct types in Julia (unlike Matlab)
  * There is no distinction between a column vector and a row vector (unlike Matlab).
  * `Array`s (and thus vectors and matrices) can hold any type. 

We'll focus on vectors and matrices of numeric types, with a bit about other element types at the end. 


## Constructing vectors

### from lists

Vectors can be constructed by listing their elements between square brackets, separated by commas or semicolons. The type of the elements is determined by promoting to a common numeric type that can hold all the listed elements (defaulting to `Int64` and `Float64` on 64-bit computers). 

``` 
x = [2, 3, 4]     # a vector of Int64s

x = [2; 3; 4]     # a vector of Int64s (identical to above)

x = [2.0; 3; 4]   # a vector of Float64s

x = [2; 3f0; 4]   # a vector of Float32s

x = [true; false; true; true] # a vector of Bools
```

Note that separating n elements by *spaces* produces a 1 x n matrix, not an n-vector!

```
x = [2 3 4]       # a 1 x 3 matrix of Int64s!!
```

### from initializing functions

```
x = zeros(3)          # a 3-vector of Float64 zeros

x = ones(4)           # a 4-vector of Float64 ones

x = randn(7)          # a 7-vector of normally distributed Float64s  

x = zeros(Int64, 8)   # an 8-vector of Int64 zeros

x = trues(5)          # a 5-vector of Bool trues
```

In [16]:
[true; false]

2-element Array{Bool,1}:
  true
 false

In [10]:
x = [2, 3, 4]    # a vector of Int64s

3-element Array{Int64,1}:
 2
 3
 4

In [6]:
x = [2; 3; 4]    # vector of Int64s

3-element Array{Int64,1}:
 2
 3
 4

In [3]:
x = [2, 3.3, 4]  # a vector of Float64s

3-element Array{Float64,1}:
 2.0
 3.3
 4.0

In [14]:
x = [1f0 ; 0 ; -7]  # a vector of Float32s

3-element Array{Float32,1}:
  1.0
  0.0
 -7.0

Note that separating by spaces does not produce a vector! It produces a 1 x n matrix instead!

In [15]:
x = [8 0 2]

1×3 Array{Int64,2}:
 8  0  2